## Set default image, imageTag, and imagePullPolicy. mode is used to indicate the
##
image:
  repository: doitandbedone/ispyagentdvr
  tag: latest
  pullPolicy: IfNotPresent

## Additional arguments to pass to agent dvr binary
extraArgs: []

updateStrategy: Recreate

service:
  swarmPort: 9401
  apiPort: 9501
  gatewayPort: 9080

environment:

appVolumeMounts:
  staging:
    emptyDir: true
    mountPath: "/export"
  data:
    emptyDir: true
    mountPath: "/data/agent"

