appVolumeMounts:
  data:
    emptyDir: true
    mountPath: /data/agent
  staging:
    emptyDir: true
    mountPath: /export
dnsConfig:
  options: []
emptyDirVolumes: true
environmentVariables: []
extraArgs: []
image:
  pullPolicy: IfNotPresent
  repository: doitandbedone/ispyagentdvr
  tag: latest
service:
  apiPort: 30951
  gatewayPort: 30980
  swarmPort: 30941
updateStrategy: Recreate
